### ISSUE TITLE
Local Parameter

### ISSUE THREAD

**Issue by RyanDirgantara** [kkelchte/hector_quadrotor#1]
Hello there!

how do you exactly play with the local parameter?

Thank you

**Comment by kkelchte** [comment]
Hi Ryan,
can you be more specific what parameter you mean exactly?
I did not change that much from the original hector quadrotor. I
 added a new quadcopter model with extra kinects and kept it up to date with new ROS versions.

**Comment by RyanDirgantara** [comment]
Hello! Thanks for the reply 

I noticed i can change the mass and inertia in the urdf and it would affect the movement of the quadcopter in the simulation, is there any other parameter I can play with beside those? because for some reason when i spawn the quadrotor it slowly rotate clockwise in the Z axis, i think there might be something wrong with the urdf.

Also is there a launch file to spawn the ardrone or the bebop model?

Thank you so much!

**Comment by kkelchte** [comment]
Hi Ryan,
the bebop (watch out, I named it like this for my own convenience, though the parameters are far from similar to the real bebop).

Anything you want, you can change in the urdf.

I use the package in combination with my 'simulation-supervised' package:
https://github.com/kkelchte/simulation_supervised

It serves as a domain shift benchmark of which you can find more information here:
kkelchte.github.io/doshico

**Comment by RyanDirgantara** [comment]
Okay! Thank you very much for the help! :)
